# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
