# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='stores',
            field=models.ManyToManyField(to='stores.Store'),
        ),
    ]
