# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('malls', '0003_mall_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
            preserve_default=False,
        ),
    ]
