# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_score'),
        ('malls', '0005_auto_20200412_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.Review'),
        ),
    ]
