# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0006_auto_20200414_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='malls'),
        ),
    ]
