# -*- coding: utf-8 -*-
# Generated by Django 3.0.5 on 2020-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0007_mall_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='trivia',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='mall',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
